# Generated by Django 4.2.5 on 2023-09-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='file',
            new_name='video',
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default=2, upload_to='about/image'),
            preserve_default=False,
        ),
    ]
