# Generated by Django 4.2.5 on 2023-09-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_file_about_video_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='video',
            field=models.URLField(),
        ),
    ]
