# Generated by Django 4.2.5 on 2023-09-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_about_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
