# Generated by Django 4.2.5 on 2023-09-27 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='professions',
            new_name='profession',
        ),
    ]
