# Generated by Django 4.2.5 on 2023-09-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_image_portfolio_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default=2, upload_to='images/Team'),
            preserve_default=False,
        ),
    ]
