# Generated by Django 4.2.5 on 2023-09-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='facebook',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkedin',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter',
            field=models.CharField(max_length=200),
        ),
    ]
