# Generated by Django 4.2.5 on 2023-09-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_address_contact_address_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='emai_1',
            new_name='email_1',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='emai_2',
            new_name='email_2',
        ),
        migrations.AddField(
            model_name='contact',
            name='icon',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
