# Generated by Django 4.2.5 on 2023-09-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_email_1_contact_docs_remove_contact_address_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='docs_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
